### ISSUE TITLE
Failing install on Komodo edit

### ISSUE THREAD

**Issue by garak** [Defman21/kobuntu-komodo#2]
On a fresh install of Komodo edit (see below), I'm getting the following error when I try to open Kobuntu.ksf:
```
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [koIScintillaSchemeService.loadSchemeFromURI]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://komodo/content/library/open.js :: open_openURIAtLine :: line 223"  data: no]
```

build info: `Komodo Edit, version 10.0.1, build 17276, platform linux-x86_64. Built on Wed Jun 15 08:25:28 2016.`

**Comment by Defman21** [comment]
Have you tried to install it using Commando? That looks like a bug in Komodo.

**Comment by garak** [comment]
Yes, it works using Commando.
Thank you
